version: "3.9"

services:
  #  Сервис 1: Elasticsearch 
  elasticsearch:
    image: elasticsearch:8.16.0
    container_name: practice01-elasticsearch
    restart: unless-stopped

    environment:
      - node.name=es-node-1
      - cluster.name=practice-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.ml.enabled=false

    ports:
      - "9200:9200"
      - "9300:9300"

    volumes:
      - es_data:/usr/share/elasticsearch/data

    deploy:
      resources:
        limits:
          memory: 1G

    ulimits:
      memlock:
        soft: -1
        hard: -1

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:9200/_cluster/health || exit 1"
        ]
      interval: 15s
      timeout: 10s
      retries: 5

  #  Сервис 2: Kibana (веб-интерфейс) 
  kibana:
    image: kibana:8.16.0
    container_name: practice01-kibana
    restart: unless-stopped

    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

    ports:
      - "5601:5601"

    depends_on:
      elasticsearch:
        condition: service_healthy

    deploy:
      resources:
        limits:
          memory: 1G

volumes:
  es_data:
    driver: local