version: "3.9"

services:
  mongodb:
    image: mongo:7
    container_name: practice01-mongodb
    restart: unless-stopped

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: practice_db

    ports:
      - "27017:27017"

    volumes:
      - mongodb_data:/data/db

    command: mongod --wiredTigerCacheSizeGB 0.5

    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--eval",
          "db.adminCommand('ping')",
          "-u",
          "admin",
          "-p",
          "secret",
          "--authenticationDatabase",
          "admin",
          "--quiet"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    image: mongo-express:1-20-alpine3.19
    container_name: practice01-mongo-express
    restart: unless-stopped

    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_URL: mongodb://admin:secret@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin

    ports:
      - "8082:8081"

    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongodb_data:
    driver: local